---
audit:
 primary datasource: <specify the data source that is the primary target of this audit>

data sources: 
- <enumerate data sources to query, collate and report on>

database: 
 path: database/assets.db
 retention days: 90
 
Malwarebytes:
 client id: <client id>
 client secret: <client secret>
 account id: <account id>
 groups:
  - <group name>

Tenable:
 access key: <access key>
 secret key: <secret key>

DNS:
 server: <server>
 zone: <zone>

Snipe-IT:
 url: <url>
 personal access token: <token>

DHCP:
 server: <server>